#!/bin/bash -x

srun -N1 -p booster --account=hai_ai_4_eo --gres gpu:1 --time=23:59:00 --pty singularity exec --bind "${PWD}:/mnt" --nv ../hyperview_latest.sif python main_ssl.py -t 0.10 -m 0 -c 6 -l 0.000500 -b 32 -w 224 -p --num-epochs 109 --train-dir 'train_data/train_data/' --label-dir 'train_data/train_gt.csv' --eval-dir 'test_data/' --out-dir 'modeldir/' &
srun -N1 -p booster --account=hai_ai_4_eo --gres gpu:1 --time=23:59:00 --pty singularity exec --bind "${PWD}:/mnt" --nv ../hyperview_latest.sif python main_ssl.py -t 0.10 -m 0 -c 6 -l 0.000250 -b 32 -w 224 -p --num-epochs 109 --train-dir 'train_data/train_data/' --label-dir 'train_data/train_gt.csv' --eval-dir 'test_data/' --out-dir 'modeldir/' &
srun -N1 -p booster --account=hai_ai_4_eo --gres gpu:1 --time=23:59:00 --pty singularity exec --bind "${PWD}:/mnt" --nv ../hyperview_latest.sif python main_ssl.py -t 0.10 -m 0 -c 6 -l 0.000125 -b 32 -w 224 -p --num-epochs 109 --train-dir 'train_data/train_data/' --label-dir 'train_data/train_gt.csv' --eval-dir 'test_data/' --out-dir 'modeldir/' &
srun -N1 -p booster --account=hai_ai_4_eo --gres gpu:1 --time=23:59:00 --pty singularity exec --bind "${PWD}:/mnt" --nv ../hyperview_latest.sif python main_ssl.py -t 0.10 -m 0 -c 6 -l 0.000050 -b 32 -w 224 -p --num-epochs 109 --train-dir 'train_data/train_data/' --label-dir 'train_data/train_gt.csv' --eval-dir 'test_data/' --out-dir 'modeldir/' &
srun -N1 -p booster --account=hai_ai_4_eo --gres gpu:1 --time=23:59:00 --pty singularity exec --bind "${PWD}:/mnt" --nv ../hyperview_latest.sif python main_ssl.py -t 0.10 -m 0 -c 6 -l 0.000025 -b 32 -w 224 -p --num-epochs 109 --train-dir 'train_data/train_data/' --label-dir 'train_data/train_gt.csv' --eval-dir 'test_data/' --out-dir 'modeldir/' &
srun -N1 -p booster --account=hai_ai_4_eo --gres gpu:1 --time=23:59:00 --pty singularity exec --bind "${PWD}:/mnt" --nv ../hyperview_latest.sif python main_ssl.py -t 0.01 -m 0 -c 6 -l 0.000500 -b 32 -w 224 -p --num-epochs 109 --train-dir 'train_data/train_data/' --label-dir 'train_data/train_gt.csv' --eval-dir 'test_data/' --out-dir 'modeldir/' &
srun -N1 -p booster --account=hai_ai_4_eo --gres gpu:1 --time=23:59:00 --pty singularity exec --bind "${PWD}:/mnt" --nv ../hyperview_latest.sif python main_ssl.py -t 0.01 -m 0 -c 6 -l 0.000250 -b 32 -w 224 -p --num-epochs 109 --train-dir 'train_data/train_data/' --label-dir 'train_data/train_gt.csv' --eval-dir 'test_data/' --out-dir 'modeldir/' &
srun -N1 -p booster --account=hai_ai_4_eo --gres gpu:1 --time=23:59:00 --pty singularity exec --bind "${PWD}:/mnt" --nv ../hyperview_latest.sif python main_ssl.py -t 0.01 -m 0 -c 6 -l 0.000125 -b 32 -w 224 -p --num-epochs 109 --train-dir 'train_data/train_data/' --label-dir 'train_data/train_gt.csv' --eval-dir 'test_data/' --out-dir 'modeldir/' &
srun -N1 -p booster --account=hai_ai_4_eo --gres gpu:1 --time=23:59:00 --pty singularity exec --bind "${PWD}:/mnt" --nv ../hyperview_latest.sif python main_ssl.py -t 0.01 -m 0 -c 6 -l 0.000050 -b 32 -w 224 -p --num-epochs 109 --train-dir 'train_data/train_data/' --label-dir 'train_data/train_gt.csv' --eval-dir 'test_data/' --out-dir 'modeldir/' &
srun -N1 -p booster --account=hai_ai_4_eo --gres gpu:1 --time=23:59:00 --pty singularity exec --bind "${PWD}:/mnt" --nv ../hyperview_latest.sif python main_ssl.py -t 0.01 -m 0 -c 6 -l 0.000025 -b 32 -w 224 -p --num-epochs 109 --train-dir 'train_data/train_data/' --label-dir 'train_data/train_gt.csv' --eval-dir 'test_data/' --out-dir 'modeldir/' &
